### ISSUE TITLE
Add missing `privacy-policy`

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication-site#168]
In the bottom of the site landing page, we have a privacy policy link.

![image](https://user-images.githubusercontent.com/91742238/168460922-ff868469-ba13-49d4-82aa-7c50de2e0d8b.png)

when trying to access https://amplication.com/privacy-policy we receive 404 error (page not found).

![image](https://user-images.githubusercontent.com/91742238/168460953-2d4484e5-fdf1-47b5-94c9-b8a9387fb207.png)

please import the privacy policy from the old site (amplication/site repository)

**Comment by Pranay-Tej** [comment]
Hi, I would like to work on this.

**Comment by tupe12334** [comment]
@Pranay-Tej Go ahead! i will assign you
