### ISSUE TITLE
update docs redirect

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication-site#194]
We got a review from the SEO agency that the following redirects are missing:

 https://amplication.com/docs/getting-started | https://docs.amplication.com/docs/getting-started/ |
 --- | --- |
https://amplication.com/docs/sync-with-github | https://docs.amplication.com/docs/sync-with-github/ |
https://amplication.com/docs/deploy | https://docs.amplication.com/docs/deploy/ |
https://amplication.com/docs/cli | https://docs.amplication.com/docs/cli/ |

make a rule that will redirect all https://amplication.com/docs to https://docs.amplication.com/docs

**Comment by yuval-hazaz** [comment]
Just to make sure, we have a list of more than 50 pages like this. we need to make sure we are creating a generic redirect for all pages with this pattern
